package pl.budzet.domowy.destop;

public enum Menu {
    DODAJ_PRZYCHOD,
    DODAJ_WYDATEK,
    WYSWIETL_PRZYCHODY,
    WYSWIETL_WYDATEKI,
    WYSWIETLANIE_Z_PRZEDZIALU_CZASU,
    WIEKSZE_OD_TWOJEJ_CENY,
    KONIEC;
}
